In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("globalAirQuality.csv")
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [5]:
df[df["city"] == "Zurich"]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
17640,2025-11-04 18:25:17.554219,CH,Zurich,47.377,8.542,37.787,104.854,23.550,11.285,17.016,0.614,104,34.719,46.797,9.232
17641,2025-11-04 19:25:17.554219,CH,Zurich,47.377,8.542,33.621,86.035,14.537,8.966,49.241,1.133,86,32.058,88.797,1.476
17642,2025-11-04 20:25:17.554219,CH,Zurich,47.377,8.542,68.172,105.368,19.422,5.672,47.163,0.655,136,16.829,49.257,3.844
17643,2025-11-04 21:25:17.554219,CH,Zurich,47.377,8.542,22.468,126.858,28.478,8.208,41.994,0.756,126,11.519,79.811,1.452
17644,2025-11-04 22:25:17.554219,CH,Zurich,47.377,8.542,35.714,70.926,37.095,6.293,66.471,1.107,92,27.309,85.689,7.126
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [7]:
df[df["aqi"] < 30]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
533,2025-11-11 23:25:17.554219,US,Los Angeles,34.052,-118.244,13.750,22.987,9.348,5.963,42.148,1.116,27,23.191,74.563,1.897
892,2025-11-11 22:25:17.554219,GB,London,51.507,-0.128,11.285,29.081,9.810,5.389,46.610,0.980,29,24.416,75.797,1.477
960,2025-11-14 18:25:17.554219,GB,London,51.507,-0.128,8.120,11.816,6.109,4.207,47.636,0.580,16,34.853,83.337,2.127
6115,2025-11-19 13:25:17.554219,SA,Riyadh,24.714,46.675,2.018,29.545,10.465,9.660,67.912,0.650,29,25.113,54.454,7.678
9914,2025-11-12 20:25:17.554219,CN,Shanghai,31.230,121.474,1.471,16.137,11.068,3.256,40.534,1.091,27,9.749,53.418,8.656
10715,2025-11-16 05:25:17.554219,SG,Singapore,1.352,103.820,8.700,29.423,8.758,9.810,36.869,1.150,29,5.489,62.381,5.607
10997,2025-11-12 23:25:17.554219,TH,Bangkok,13.756,100.502,8.853,27.697,6.859,4.289,27.970,0.670,27,19.872,34.930,3.871
15279,2025-11-11 09:25:17.554219,US,San Francisco,37.775,-122.419,13.087,7.782,8.638,3.500,51.672,0.294,26,17.194,33.030,3.104

In [15]:
# quering data
df.query("temperature > 30 & aqi < 30")[["city"]]

       city
960  London